### ISSUE TITLE
Which compressed folder is the test set of MIMIC-CXR dataset?

### ISSUE THREAD

**Issue by FRENKIE-CHIANG** [baeseongsu/mimic-cxr-vqa#2]
Hello, since the MIMIC-CXR dataset is too large to download, I only need the test set. Which compressed folder is the test set of this dataset?

**Comment by baeseongsu** [comment]
Hi, @FRENKIE-CHIANG. Thank you for using the MIMIC-CXR-VQA dataset! To access the test set of MIMIC-CXR-VQA dataset, please follow these steps:

1. **Construct the `test.json` File**: Execute the script provided below. (For more details, refer to [how to access](https://github.com/baeseongsu/mimic-cxr-vqa?tab=readme-ov-file#accessing-the-mimic-cxr-vqa-dataset))

```bash
bash download_and_build_dataset.sh
```

2. **Modify the `download_images.sh` Script**: After obtaining the test.json file, you need to modify the `download_images.sh` script to ensure only the test set is downloaded. Considering the large scale of the MIMIC-CXR-JPG dataset you mentioned, this revision enables downloading a smaller subset of images. Modify the script as follows:

- (before)

https://github.com/baeseongsu/mimic-cxr-vqa/blob/b177ce81bc37826b0c44bef9950a13ec9151fac5/download_images.sh#L32-L38

- (after)

```bash
# Gather image paths from the test JSON dataset file
image_paths_test=$(get_image_paths 'mimiccxrvqa/dataset/test.json')

# Set the script to use only the test set image paths
image_paths=$(echo -e "$image_paths_test")
```

---

If you encounter any problems with these steps or experience any inconvenience, please let us know.

**Comment by FRENKIE-CHIANG** [comment]
Thanks for your reply. I have got the image data(MIMIC-CXR-JPG)， but in this dataset, there are no txt files about the caption or VQA-test data for the images. I found that these txt files are in the MIMI-CXR dataset(not in&nbsp;MIMIC-CXR-JPG). But for some reasons, I cannot get the MIMIC-CXR-JPG now. I'm so sorry but I need the txt files&nbsp;corresponding to the images&nbsp;urgently. Could you please provide me with the corresponding txt file of images (including caption and VQA text), or provide me with a convenient download path, so that I can only download txt files, not image files. If you can help me, I will be most grateful to you, thank you so much!!!
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Apr 2, 2024 01:46 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [baeseongsu/mimic-cxr-vqa] Which compressed folder is the test set of MIMIC-CXR dataset? (Issue #2)

&nbsp;



 
Hi, @FRENKIE-CHIANG. Thank you for using the MIMIC-CXR-VQA dataset! To access the test set of MIMIC-CXR-VQA dataset, please follow these steps:
  
Construct the test.json File: Execute the script provided below. (For more details, refer to how to access)
  bash download_and_build_dataset.sh
  
Modify the download_images.sh Script: After obtaining the test.json file, you need to modify the download_images.sh script to ensure only the test set is downloaded. Considering the large scale of the MIMIC-CXR-JPG dataset you mentioned, this revision enables downloading a smaller subset of images. Modify the script as follows:
   
(before)
  
https://github.com/baeseongsu/mimic-cxr-vqa/blob/b177ce81bc37826b0c44bef9950a13ec9151fac5/download_images.sh#L32-L38
  
(after)
  # Gather image paths from the test JSON dataset file image_paths_test=$(get_image_paths 'mimiccxrvqa/dataset/test.json') # Set the script to use only the test set image paths image_paths=$(echo -e "$image_paths_test")
 
 
If you encounter any problems with these steps or experience any inconvenience, please let us know.

**Comment by baeseongsu** [comment]
Hi, @FRENKIE-CHIANG!

- For downloading the corresponding radiology report (which can be viewed as the "caption") of an image in MIMIC-CXR, there are two methods: 
  - (Method 1) Use the `wget` command to download only the report dataset: `wget -r -N -c -np --user ${user} --ask-password https://physionet.org/files/mimic-cxr/2.0.0/mimic-cxr-reports.zip`
  - (Method 2) Click on `mimic-cxr-reports.zip` and download the file from https://physionet.org/content/mimic-cxr/2.0.0/.

- For access to the VQA-test data of MIMIC-CXR-VQA, please refer to [how to access](https://github.com/baeseongsu/mimic-cxr-vqa?tab=readme-ov-file#accessing-the-mimic-cxr-vqa-dataset). Through this process, you can obtain the final `test.json` file.

--- 

As these datasets are under the PhysioNet Credentialed Health Data License 1.5.0, please be aware that we cannot directly upload the entire dataset freely.

**Comment by FRENKIE-CHIANG** [comment]
Your kind help has solved my urgent problem Thank you very much! Wish you a happy day! Thanks again!!!!!!!!&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Apr 5, 2024 04:56 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [baeseongsu/mimic-cxr-vqa] Which compressed folder is the test set of MIMIC-CXR dataset? (Issue #2)

&nbsp;



 
Hi, @FRENKIE-CHIANG!
  
 
For downloading the corresponding radiology report (which can be viewed as the "caption") of an image in MIMIC-CXR, there are two methods:
  
(Method 1) Use the wget command to download only the report dataset: wget -r -N -c -np --user ${user} --ask-password https://physionet.org/files/mimic-cxr/2.0.0/mimic-cxr-reports.zip
 
(Method 2) Click on mimic-cxr-reports.zip and download the file from https://physionet.org/content/mimic-cxr/2.0.0/.
  
 
 
For access to the VQA-test data of MIMIC-CXR-VQA, please refer to how to access. Through this process, you can obtain the final test.json file.
 
  
 
As these datasets are under the PhysioNet Credentialed Health Data License 1.5.0, please be aware that we cannot directly upload the entire dataset freely.
