### ISSUE TITLE
differences to ehrxqa

### ISSUE THREAD

**Issue by JunMa11** [baeseongsu/mimic-cxr-vqa#3]
Hi @baeseongsu ,

Thanks for sharing the great resource. 

could you please share the main differences of this data compared to the following one?

https://github.com/baeseongsu/ehrxqa

**Comment by baeseongsu** [comment]
Dear @JunMa11,

The main differences between MIMIC-CXR-VQA and EHRXQA are:
- MIMIC-CXR-VQA  is a medical VQA dataset, while EHRXQA is a multi-modal QA dataset based on EHRs, including images and tables.
- MIMIC-CXR-VQA  involves answering questions about a single chest X-ray image (Image, Question $\rightarrow$ Answer), whereas EHRXQA requires reasoning over a database of images and tables from patients' records to answer questions.
- MIMIC-CXR-VQA  serves as a medical VQA benchmark or instruction-tuning dataset for VLMs, while EHRXQA is a comprehensive QA benchmark for evaluating a system's ability to understand and extract information from multi-modal medical data.

For more details, please refer to Figure 1 and the dataset examples in the [paper](https://arxiv.org/abs/2310.18652) :D

Best,
Seongsu

**Comment by JunMa11** [comment]
Dear @baeseongsu ,

Thank you so much for your detailed explanation!
